Graph based models
bluemarblepayroll/dbee pull request #33
Opened 2021-02-23 17:51 UTC by gerryster

WIP

2021-02-23 18:04 UTC, gerryster commented on lib/dbee/model/relationships.rb
> +      register 'basic', Basic
I currently only have a use-case for one type of relationship. This seemed to be a reasonable way of handling this scenario for an acts as hashable class. However, I am open to feedback here.

2021-02-23 19:38 UTC, gerryster commented on spec/dbee/base_spec.rb
> -      key_paths = %w[
Many of these tests have been moved to dsl_schema_builder_spec.rb.

2021-02-23 19:41 UTC, gerryster commented on spec/fixtures/models.yaml
> +  a:
I like the new succinctness of this particular model in graph based form.

2021-02-23 19:55 UTC, gerryster commented on README.md
> +  from: 'practice',
This field is now required unless using tree based models. It would be also possible to infer the starting point/from model when `to_sql` is called with a `Dbee::Base` instance. Let me know if you think this is worth pursuing.

2021-02-24 17:32 UTC, gerryster commented
Update: my plan is to have `Dbee.to_sql` infer the "from" model when given a Dbee::Base DSL model. We do have an internal use-case for this.

2021-03-02 23:38 UTC, mattruggio requested changes
This looks like a wonderful addition and fixes a core fundamental issue with the first implementation: the underlying data structure makes more sense as a graph and not a tree.  I left some comments throughout the files.  The ones that stand out the most:

1. hash-based API broken for main Dbee#sql call.  This should work for both tree and graph-based hash objects.
2. key-first relationships to match new key-first modeling API.
3. Indifferent key support for hashes (string and symbols)

Overall I am pretty excited for this update.

2021-03-03 20:28 UTC, mattruggio commented on README.md
> +  from: 'practice',
I think this works.

2021-03-03 22:21 UTC, gerryster commented on lib/dbee/model.rb
> +      # TODO: raise an error if two relationships share a name
My plan is to take care of this in the follow on PR which allows for relationships to be specified by a hash keyed by relationship name.

2021-03-03 22:36 UTC, gerryster commented on lib/dbee.rb
> +      raise ArgumentError, 'query requires a from model name' unless query.from
I'll add some basic empty string validation. I also wanted to point out that the activerecord provider will raise a `Dbee::Model::ModelNotFoundError` if the from field in the query refers to something which is not known.

2021-03-04 16:45 UTC, gerryster commented on lib/dbee/model/relationships/basic.rb
> +          @name = name || raise(ArgumentError, 'name is required')
I'll add validation.

2021-03-04 16:46 UTC, gerryster commented on lib/dbee/schema_from_tree_based_model.rb
> +        graph_model_attrs[:relationships].push({
Yea, what I had was ugly. Since there isn't much here, I put the push params on the same line.

2021-03-04 16:48 UTC, gerryster commented on lib/dbee/schema_creator.rb
> +  # 3. The hash representation of a tree based model.
Yep, item #1 in the list mentions the support for the hash representation of a schema. I didn't add Dbee::Schema instances to this list as those are passed through.

2021-03-04 22:45 UTC, gerryster commented on lib/dbee/schema_creator.rb
> +    def make_schema(input)
Ouch! Thanks for catching a bug. I didn't consider the case of a tree based hash with no child models. I improved the hash detection to account for this and added a unit test to the schema_creator_spec to account for this.

2021-03-04 22:47 UTC, gerryster commented on lib/dbee/schema_creator.rb
> +      if input.key?(:models) && input[:models].is_a?(Array)
Good point. I ended up changing this method to instead look at the "name" key and it now handles both types.

2021-03-06 18:14 UTC, gerryster commented on lib/dbee.rb
> +    def sql(schema_or_model, query_input, provider)
This has been addressed in commit 80cd1ec .

2021-03-08 15:50 UTC, gerryster commented on README.md
> +  from: 'practice',
FYI: I did implement the logic to infer the "from" query if a Dbee::Base instance is provided.

2021-03-08 15:51 UTC, gerryster commented
@mattruggio : this is ready for another look. Also, I am going to create a follow on PR soon which turns the "relationship" specification into a hash.

2021-03-08 19:53 UTC, mattruggio approved these changes

2021-03-08 19:53 UTC, mattruggio commented
LGTM

2021-03-11 17:27 UTC, merged